// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cUIMIA() {
    driver.get("https://demoqa.com/");
    driver.manage().window().setSize(new Dimension(1552, 928));
    driver.findElement(By.cssSelector("a:nth-child(1) path")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".show #item-4 .text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".show #item-3 .text")).click();
    driver.findElement(By.id("addNewRecordButton")).click();
    {
      WebElement element = driver.findElement(By.id("addNewRecordButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("xanh");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("le");
    driver.findElement(By.id("userForm")).click();
    driver.findElement(By.id("userEmail")).click();
    driver.findElement(By.id("userEmail")).sendKeys("xanhxanhxanh@gmail.com");
    driver.findElement(By.id("age")).click();
    driver.findElement(By.id("age")).sendKeys("20");
    driver.findElement(By.id("salary")).click();
    driver.findElement(By.id("salary")).sendKeys("18888888");
    driver.findElement(By.id("department")).click();
    driver.findElement(By.id("department")).sendKeys("IT");
    driver.findElement(By.id("submit")).click();
    {
      WebElement element = driver.findElement(By.id("submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("footer")).click();
    driver.findElement(By.cssSelector("footer")).click();
    driver.findElement(By.cssSelector("footer")).click();
  }
}
